env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
extends:
  - airbnb
rules:
  prefer-rest-params: 0
  arrow-parens:
    - error
  arrow-body-style:
    - error
    - always
  strict:
    - off